### ISSUE TITLE
Awesome azd Template Gallery Site - MVP Design Work

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/awesome-azd#28]
### Related Links
- [Awesome AZD Templates Site](https://azure.github.io/awesome-azd/)
- [Experience Audit Figjam](https://www.figma.com/file/G0JavvOwFRUyAf47wyiW0k/Awesome-Azd-Templates----Experience-Audit?node-id=301%3A227)

### Task List
- [x] Conduct experience audit of the initial release of the Awesome AZD template site
- [x] Capture pain points and summarize into themes
- [x] Capture ideas for improvement and prioritize
- [x] Create roadmap to complete design work for MVP

##### Oct 17 - 21
- [x] Prioritization + Ideation
- [x] Design Roadmap
- [x] Site Map Proposals
- [x] Content Mapping (Filters, Content on Pages)

##### Oct 24 - 28
- [x] Navigation Pattern
- [x] Filter Categories & Groupings
- [x] Filter & Search Patterns
- [x] Card Patterns

##### Oct 31 - Nov 4
- [x] Tie up card patterns 
- [x] Tie up filter patterns
- [x] Template page layout
- [x] Template page Hero Copy
- [x] Template page CTA to submit a template

##### Nov 10 - Nov 14
- [x] Visual Design 
- [ ] Accessibility
- [ ] Mobile
- [ ] Getting Started Page (Time Permitting)
- [ ] About/Landing Page (Time Permitting)
- [ ] Resources Page (Time Permitting)
- [x] Review with Savannah & Team

### Prioritized ideas
- [ ] We'd like to have something nicer looking for when the template author hasn't included an architecture diagram

**Comment by savannahostrowski** [comment]
![image](https://user-images.githubusercontent.com/8949415/194944678-02d3e336-d8dd-4b0c-bf75-8a67e8ad0910.png)

**Comment by Austinauth** [comment]
@savannahostrowski I like converting this issue to an audit of the overall site 🎉 We'll have to discuss scoping and timelines during our sync later this afternoon.

A few quick notes on the placeholder image for the architecture diagram

- I have no issue making something quick for the interim that we can use immediately
- Long term I think we should look at whether the preview image is even useful at all in its current state. For most of the templates the architecture diagrams are too big and detailed to really be distinguishable on the tile view. Some of them are even cropped. Will investigate this further as part of the overall audit 👍🏼

**Comment by Austinauth** [comment]
**Update 10/17/2022**
This update covers the work completed last week.

- Completed initial audit of the Awesome AZD site experience (observations, questions, pain points,)
- Summarized core pain points into 5 themes
- Completed initial ideation for each pain point (below the themes)
- Reviewed inspiration sites & started rough sketching
- **This week:** Savannah and I to meet to vote on the list of ideas and prioritize together.
- **This week:** Begin creating design concepts and artifacts based on the ideas we prioritize

**Comment by Austinauth** [comment]
**Update 11/07/2022**

This update covers work completed last week. Project remains on schedule. Primary focus going into week 4 will be around completing the visual design.

- Completed initial prototype
- Received critique from both design and PM stakeholders
- Additional focus to be placed on detail page design exploration
- **This week:** Tweaking UX based on feedback
- **This week:** Syncing with Nitya to discuss implementation plans and scope
- **This week:** Exploring detail page designs + interactions for each template
- **This week:** Exploring contribution CTA placement
- **This week:** Begin visual design explorations (Fluent 2)

**Comment by Austinauth** [comment]
**Update 12/05/2022**
- Completed initial pass at the visual design 
- Needs review with PM & Development team to determine next steps/timelines
- **Outstanding:** Requested template experience
- **Outstanding:** Mobile experience

**Comment by Austinauth** [comment]
I will be updating this issue with redlines and detailed guidance for each component over the next few days!

<hr>

**Meeting w/Marina to discuss implementation**

- For now use this issue. @hemarina to make new dev issue in the future.
- Used the [Fluent design system](https://developer.microsoft.com/en-us/fluentui#/controls/web) for components.
- Design prototype can be found [here](https://www.figma.com/file/KYGTwUWjpgRzAxPtk05Qqz/Awesome-azd-Website?node-id=107%3A141388&t=ZoIXWOCJtMHap00i-1) on the > _MVP Template Page Prototype_ page.

## Page components
  
The awesome azd template page can be broken into chunks/components we deliver one by one.
 
 _Disclaimer 1: All chunks feature a light/dark mode._
 _Disclaimer 2: Fluent components should work for mobile, I'll create mobile mockups ASAP._
 
 ### 1. Global Navigation
 
 **Figure 1. A**
 ![image](https://user-images.githubusercontent.com/6994218/213013616-82b85851-a5cf-4956-9308-4524d2e00645.png)

 **Figure 1. B**
![image](https://user-images.githubusercontent.com/6994218/213013771-a86adcb6-7558-4a7f-87f7-9cec2f3cf534.png)

Details
- Global navigation is sticky when you scroll.
- An additional sticky bar featuring search & filter tags is added below the global navigation bar once the user has scrolled past the hero section (see Figure 1.B).

### 2. Hero/Search
![image](https://user-images.githubusercontent.com/6994218/213014113-f95d21fc-90bc-435d-8a42-dc60b13ec80a.png)

States:
- Empty
- Populated
- Searched (results)
- Searched (no results)

**3. Filters (side)**
![image](https://user-images.githubusercontent.com/6994218/213014731-5350540c-ab33-4fc2-b2c7-c0038a14fff2.png)

**4. Sorting + filter bar (across the top)**
![image](https://user-images.githubusercontent.com/6994218/213014805-73f868c9-c08c-40de-baab-4505ebd5e143.png)

![image](https://user-images.githubusercontent.com/6994218/213015018-86923314-985a-43f1-b698-9f1bc618e7c7.png)

 **5. Card layout**
![image](https://user-images.githubusercontent.com/6994218/213015189-2d25a31b-4024-4de0-9966-f6d57b48b663.png)

 **6. Call to action card layout**
![image](https://user-images.githubusercontent.com/6994218/213015656-9e5718fc-22a8-47ef-80f1-883b8367f9a9.png)

 **7. Slide out panel**

**Comment by savannahostrowski** [comment]
I think this breakdown makes sense at the epic level - we can break each one of these chunks down as engineering work requires.

@hemarina I may help out a little here and there (I used to be a React dev!) but will give you a heads up. 

@Austinauth Let's copy these chunks into separate tickets and turn this into an epic so that folks can assign (also good to let open-source contributors help!)
